### PR TITLE
Replace lists to generators

### PR DESCRIPTION
**Pull request by rominf**

### CODE REVIEW

**Comment by EmilStenstrom** [comment]
@rominf Thanks! Could you tell me a little bit more about your use case for generators instead of lists?

**Comment by rominf** [comment]
In Python 3 (in comparison to Python 2) all built in functions return generators instead of lists to improve performance. See https://wiki.python.org/moin/Generators
Moreover, conversion to a list is easy as `list(f())`.

**Comment by EmilStenstrom** [comment]
Thanks for posting this PR. I've decided not the switch to generators because I think it makes the return values look slightly unintuitive for beginners.

**Comment by aryamccarthy** [comment]
@EmilStenstrom With this PR, one could avoid slurping the entire file into memory. Instead, it would fetch one sentence at a time and let you process the input online. This can become serious for large CoNLL files; I implore you to reconsider the PR from @rominf.

**Comment by EmilStenstrom** [comment]
@aryamccarthy @rominf I see how this would be more efficient for big file. I'd like to keep the old API working, and I think returning lists make it more beginner friendly. What about adding a separate method `parse_incrementally` that returns a generator?

**Comment by aryamccarthy** [comment]
That's a good idea. I'd propose an additional modification to this PR: accepting an iterator as its argument (rather than a single, monolithic string). That way, one can read the file incrementally, too, using this pattern:

```python
with open(file_path) as f:
    sentences = parse_incrementally(f)  # Note that it's not `f.read()`, which slurps.
```

**Comment by EmilStenstrom** [comment]
Sounds excellent. Care to write up a PR?

**Comment by aryamccarthy** [comment]
I'll let @rominf handle that, since his PR is already solid so far.

**Comment by EmilStenstrom** [comment]
This PR was superseeded by #17.

**Pull request closed without merging**
