### PR TITLE
Serialization

### PR DESCRIPTION
**Pull request by erickrf**
Implemented a function `serialize_tree` to create a conllu representation of a tree.
I also moved a few functions to `__init__.py` to facilitate access and changed version number to 0.5.

### CODE REVIEW

**Comment by EmilStenstrom** [comment]
@erickrf This looks awesome! :) Only thing I'm conflicted about is the `__init__.py` stuff. Do I understand it correctly that this just allows importing stuff directly from conllu instead of from conllu.parser? Doesn't this mean there's two ways to import the same thing. I'm easily convinced, so could you tell me about your reasoning around that?

**Comment by erickrf** [comment]
Exactly! This allows the simpler `from conllu import parse, print_tree (...)`, but the complete import `from conllu.parser import parse` will still work. 

This is just to make things easier to write, especially if you just `import conll` and then call the functions directly.

**Comment by EmilStenstrom** [comment]
Awesome! Thank you for this!

**Comment by EmilStenstrom** [comment]
Released a new version 0.5 to PyPi: https://pypi.python.org/pypi/conllu

**Pull request merged**
