### PR TITLE
Update parser.py

### PR DESCRIPTION
**Pull request by svetlana21**
Allows to choose columns to parse if you have less than 10 columns in a conllu file.

### CODE REVIEW

**Comment by EmilStenstrom** [comment]
@svetlana21 Excellent! Could I ask for one more favor? If I merge this right away, some people that use parse() in their code will be missing a parameter. But if you set to_parse to a default value, all old code will continue to work. I'll take it from there and add tests and all that! Thanks again!

**Comment by svetlana21** [comment]
@EmilStenstrom Ok. It should be a list of all column names, am I right?

**Comment by EmilStenstrom** [comment]
@svetlana21 Yep!

**Comment by EmilStenstrom** [comment]
Thank you! ❤️

**Comment by EmilStenstrom** [comment]
I'll make a new release version to PyPi later this week, so we can all get this code by "pip install".

**Comment by svetlana21** [comment]
I'm so glad to make a contribution! Thank you, too :)

**Comment by EmilStenstrom** [comment]
@svetlana21 Now the new version is live! I changed some things compared to the code you submitted: 

* The parameter is called `fields` instead of `to_parse`. The format documentation talks about fields so I thought I should follow that naming.
* I now allow parsing files that have fewer fields than the ones specified without specifying the fields argument. I just takes as many columns as it can.
* I added lots of tests to make sure this never break again.

Version 0.4 is up now! https://pypi.python.org/pypi/conllu

**Comment by svetlana21** [comment]
Happy to see it! Thank you :)

**Pull request merged**
