### PR TITLE
Add nodes with negative id/head values to the parse tree

### PR DESCRIPTION
**Pull request by jamesqo**
/cc @EmilStenstrom. This is blocking me on a personal project of mine.

Fixes https://github.com/EmilStenstrom/conllu/issues/7

### CODE REVIEW

**Comment by EmilStenstrom** [comment]
Awesome. I see nothing stopping this from being merge. I'll get it done tomorrow! Thanks!

**Comment by jamesqo** [comment]
There were actually a couple of problems, but I just fixed them and added unit tests. Thanks for the quick turnover!

**Comment by EmilStenstrom** [comment]
@jamesqo I've looked through this, and it looks great. Would you mind indenting the testcase is data6_tree like a tree? I know it's a chore, but it makes the examples much easier to read.

**Comment by jamesqo** [comment]
Sure. For future reference, do you know if there's a way to configure autopep8 to automatically generate the tree fmt, or do you just do it by hand?

**Comment by jamesqo** [comment]
@EmilStenstrom I've done the formatting.

**Comment by EmilStenstrom** [comment]
Merged, and new version released to pypi: https://pypi.python.org/pypi/conllu

**Comment by jamesqo** [comment]
@EmilStenstrom Great. Thank you so much!

**Pull request merged**
